ingredient_list: ["ingredient01", "ingredient02", "ingredient03", "ingredient04"] # list of ingredient names
coaster_list: ["coaster01"] # list of coaster names
bottle_height: 0.1215 # height of bottle (meters)
bottle_radius: 0.024 # radius of bottle (meters)